### PR TITLE
Add -Xdoclint:none for javadoc plugin; increment version to 8

### PR DESCRIPTION
**Pull request by derekhulley**
Please release V8 to Maven Central.

### CODE REVIEW

**Comment by derekhulley** [comment]
We can also use a profile but I'm not sure if it's necessary or how best to wire it in.  I can investigate further, if that would be better.

```
  <profile>
     <id>doclint-java8-max</id>
     <activation>
        <jdk>[1.8,)</jdk>
     </activation>
     <build>
        <plugins>
           <plugin>
              <artifactId>maven-javadoc-plugin</artifactId>
              <configuration>
                 <!-- <additionalparam>-Xmaxwarns 10000 -Xmaxerrs 10000</additionalparam> to detect more than 100 error -->
                 <additionalparam>-Xdoclint:none</additionalparam>
              </configuration>
           </plugin>
        </plugins>
     </build>
  </profile>
```

**Comment by slanglois** [comment]
You know what, that profile does look very nice! :-)

I would do it a little differently though. 
Instead of configuring the javadoc plugin, you can just define the `additionalparam` property. First, it makes the thing a bit more concise. But more importantly, it leaves the possibility for other plugins or inheriting projects to complement this value, instead of just overriding it.

```
  <profile>
     <id>doclint-java8-max</id>
     <activation>
        <jdk>[1.8,)</jdk>
     </activation>
        <properties>
           <!-- Allow javadoc to be generated on Java8 -->
           <additionalparam>-Xdoclint:none</additionalparam>
        </properties>
  </profile>
```

I just tested it, so I can commit it if you want. (But I don't want to deprive you of your pull request ;-)

**Comment by derekhulley** [comment]
Haha.  Commit whatever is best :-)

**Comment by slanglois** [comment]
Integrated in commit 3dfa0ea48e5f31d030926edb27b34519057ab2e5 to be released in version 8.
Thanks!

**Pull request closed without merging**
